version: "3"
services:
  mariadb:
    build: ./requirement/mariadb
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/docker/volumes/mariadb
    networks:
      - "inception_network"
    env_file: .env
  nginx:
    container_name: nginx
    volumes:
        - ./data/wordpress:/var/www/wordpress
    build:
      context: ./requirement/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    networks:
      - "inception_network"
    depends_on: 
      - "wordpress"
    env_file: .env
    expose:
      - "443"
    restart: on-failure
  wordpress:
    env_file: .env
    container_name: wordpress
    build:
      context: ./requirement/wordpress
      dockerfile: Dockerfile
    volumes:
      - ./data/wordpress:/var/www/wordpress
    restart: on-failure
    expose:
      - "9000"
    networks:
      - "inception_network"
networks:
  inception_network:
    driver: bridge
volumes:
  wordpress:
  #mariadb:
    #driver: local
    #type: 'none'
    #o: 'bind'
    #device: "./data/mariadb"
