version: "3"
services:
  mariadb:
    volumes:
      - mariadb_data:/var/www/html
    build: ./requirement/mariadb
    ports:
      - "3306:3306"
    networks:
      - "inception_network"
    env_file: .env
    restart: always

  nginx:
    container_name: nginx
    volumes:
        - wordpress_data:/var/www/html
    build:
      context: ./requirement/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    networks:
      - "inception_network"
    depends_on: 
      - "wordpress"
    env_file: .env
    expose:
      - "443"
    restart: always

  wordpress:
    env_file: .env
    container_name: wordpress
    build:
      context: ./requirement/wordpress
      dockerfile: Dockerfile
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    expose:
      - "9000"
    networks:
      - "inception_network"

networks:
  inception_network:
    driver: bridge

volumes:
  wordpress_data:
  mariadb_data:
